#!/bin/bash
filename='\\*\\\\'\''Best school'\''\\\\*$\\?\\*\\*\\*\\*\\*:)'
printf "Best School\n" > "$filename"
cat "$filename"
echo "Best School" > "\\*\\\\'\"Best School\"\\'\\\\*$\\?\\*\\*\\*\\*\\*:)"
